camel:
  springboot:
    # The Camel context name
    name: orders-internal
  component:
    servlet:
      mapping:
        contextPath: /*

# Binding health checks to a different port
management:
  port: 8081

# disable all management endpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

# postgresql connection details
postgresql:
  service:
    hostname: ${PG_HOSTNAME:orders-db.namespace-name.svc }
    database: ${PG_DATABASE:orders}
    username: ${PG_USERNAME:evalsNN}
    password: ${PG_PASSWORD:password}

# database configuration
spring:
  datasource:
    url: jdbc:postgresql://${postgresql.service.hostname}:5432/${postgresql.service.database}
    username: ${postgresql.service.username}
    password: ${postgresql.service.password}